name: Calculate version number

on:
  workflow_call:
    outputs:
      semver:
        description: "workflow semantic version number"
        value: ${{ jobs.version_job.outputs.semver }}      
      semver_lowercase:
        description: "workflow semantic version number lowercased"
        value: ${{ jobs.version_job.outputs.semver_lowercase }}

jobs:
  version_job:
    name: Calculate version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Display the version
        run: |
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Change string case
        id: changecase
        uses: ASzc/change-string-case-action@v1
        with:
          string: v${{ steps.gitversion.outputs.semVer }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    outputs:
      semver: ${{ steps.gitversion.outputs.semVer }}
      semver_lowercase: ${{ steps.changecase.outputs.lowercase }}
    