name: Package and publish helm charts to oci-based registries

on:
  workflow_call:
    inputs:
      chart_semver:
        required: true
        type: string
        description: "Target sem version for the chart"
      app_version:
        required: true
        type: string
        description: "Target app version"
      source_folder:
        required: true
        type: string
        description: "Source folder for the helm chart in the repository" 

    secrets:
      SS_ACR_NAME:
        required: true
      SS_ACR_USERNAME:
        required: true
      SS_ACR_PASSWORD:
        required: true
      GHA_USERNAME:
        required: true
      GHA_TOKEN:
        required: true

jobs:
  build_job:
    name: Package and push helm chart to ACR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GHA_TOKEN }}
        id: install

      - name: login to acr using helm
        run: |
          helm registry login ${{ secrets.SS_ACR_NAME }} --username ${{ secrets.SS_ACR_USERNAME }} --password ${{ secrets.SS_ACR_PASSWORD }}

      - name: Package Helm chart and get resulting file name
        id: package_chart
        run: |
          CHART_PATH=$(helm package ${{ inputs.source_folder }} --version ${{ inputs.chart_semver }} --app-version ${{ inputs.app_version }} | grep 'Successfully packaged chart' | awk -F': ' '{print $2}')
          CHART_FILE_NAME=$(basename $CHART_PATH)
          echo "::set-output name=chart_file_name::$CHART_FILE_NAME"

      - name: Push chart to registry as OCI artifact
        run: |
          helm push ${{ steps.package_chart.outputs.chart_file_name }} oci://${{ secrets.SS_ACR_NAME }}/helm
