name: Validate and package helm chart

on:
  workflow_call:
    inputs:
      semver_lowercase:
        required: true
        type: string
        description: "Target sem version for the chart"
      source_folder:
        required: true
        type: string
        description: "Source folder for the helm chart in the repository" 
    secrets:
      GHA_USERNAME:
        required: true
      GHA_TOKEN:
        required: true

jobs:
  package_job:
    name: Validate and Package helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GHA_TOKEN }}
        id: install

      - name: Validate helm chart
        run: |
          helm lint ${{ inputs.source_folder }} 

      - name: Package Helm chart and get resulting file name
        id: package_chart
        run: |
          PKGOUT=$(mktemp -d --tmpdir=.)
          helm package ${{ inputs.source_folder }} --version ${{ inputs.semver_lowercase }} --app-version ${{ inputs.semver_lowercase }} -d $PKGOUT
          CHART_FILE_NAME=$(ls -d "$PKGOUT/"*.tgz)
          echo "::set-output name=chart_file_name::$CHART_FILE_NAME"
