name: Validate and package helm chart

on:
  workflow_call:
    inputs:
      chart_semver:
        required: true
        type: string
        description: "Target sem version for the chart"
      app_version:
        required: true
        type: string
        description: "Target app version"
      source_folder:
        required: true
        type: string
        description: "Source folder for the helm chart in the repository" 
    secrets:
      GHA_USERNAME:
        required: true
      GHA_TOKEN:
        required: true

jobs:
  package_job:
    name: Validate and Package helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GHA_TOKEN }}
        id: install

      - name: Validate helm chart
        run: |
          helm lint ${{ inputs.source_folder }} 

      - name: Package Helm chart and get resulting file name
        id: package_chart
        run: |
          CHART_PATH=$(helm package ${{ inputs.source_folder }} --version ${{ inputs.chart_semver }} --app-version ${{ inputs.app_version }} | grep 'Successfully packaged chart' | awk -F': ' '{print $2}')
          CHART_FILE_NAME=$(basename $CHART_PATH)
          echo "::set-output name=chart_file_name::$CHART_FILE_NAME"
